"""
Diagram Generator — Mermaid.js HTML 렌더러

입력: .mmd 파일 경로 또는 --all 플래그 (output/diagrams/*.mmd 전체)
출력: output/diagrams/{name}.html (브라우저에서 바로 열 수 있는 단독 HTML)

사용법:
  python3 render.py output/diagrams/campaign_flow.mmd
  python3 render.py --all                   # output/diagrams/ 내 모든 .mmd 처리
"""

import sys
import argparse
from pathlib import Path

# ─── 경로 설정 ─────────────────────────────────────────────────────────────
SKILL_DIR = Path(__file__).parents[1]
PROJECT_ROOT = Path(__file__).parents[4]
OUTPUT_DIAGRAMS = PROJECT_ROOT / "output" / "diagrams"

# ─── HTML 템플릿 ───────────────────────────────────────────────────────────
HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>{title}</title>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #f8fafc;
      display: flex;
      flex-direction: column;
      align-items: center;
      padding: 40px 20px;
      min-height: 100vh;
      margin: 0;
    }}
    h2 {{
      color: #1e293b;
      margin-bottom: 8px;
      font-size: 1.2rem;
      font-weight: 600;
    }}
    .meta {{
      color: #64748b;
      font-size: 0.8rem;
      margin-bottom: 32px;
    }}
    .diagram-box {{
      background: #ffffff;
      border: 1px solid #e2e8f0;
      border-radius: 12px;
      padding: 40px;
      box-shadow: 0 1px 8px rgba(0,0,0,.06);
      max-width: 1200px;
      width: 100%;
      overflow: auto;
    }}
    .mermaid svg {{
      max-width: 100%;
    }}
    .source-block {{
      margin-top: 24px;
      background: #1e293b;
      color: #94a3b8;
      border-radius: 8px;
      padding: 16px 20px;
      font-family: "JetBrains Mono", monospace;
      font-size: 0.78rem;
      white-space: pre;
      overflow: auto;
      max-width: 1200px;
      width: 100%;
    }}
    details > summary {{
      cursor: pointer;
      color: #64748b;
      font-size: 0.82rem;
      margin-top: 16px;
    }}
  </style>
</head>
<body>
  <h2>{title}</h2>
  <div class="meta">Generated by diagram-generator · {generated_at}</div>

  <div class="diagram-box">
    <div class="mermaid">
{mermaid_code}
    </div>
  </div>

  <details>
    <summary>Mermaid 소스 보기</summary>
    <div class="source-block">{mermaid_code_escaped}</div>
  </details>

  <script>
    mermaid.initialize({{
      startOnLoad: true,
      theme: 'base',
      themeVariables: {{
        primaryColor: '#6366f1',
        primaryTextColor: '#1e293b',
        primaryBorderColor: '#818cf8',
        lineColor: '#94a3b8',
        secondaryColor: '#f1f5f9',
        tertiaryColor: '#e0f2fe',
      }}
    }});
  </script>
</body>
</html>
"""


def render_mmd(mmd_path: Path) -> Path:
    """단일 .mmd 파일을 HTML로 변환 후 저장. 생성된 html 경로 반환."""
    mmd_path = mmd_path.resolve()
    if not mmd_path.exists():
        raise FileNotFoundError(f"파일 없음: {mmd_path}")

    raw = mmd_path.read_text(encoding="utf-8").strip()
    title = mmd_path.stem.replace("_", " ").replace("-", " ").title()

    from datetime import datetime
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    html_content = HTML_TEMPLATE.format(
        title=title,
        mermaid_code=raw,
        mermaid_code_escaped=raw.replace("<", "&lt;").replace(">", "&gt;"),
        generated_at=generated_at,
    )

    out_path = mmd_path.with_suffix(".html")
    out_path.write_text(html_content, encoding="utf-8")
    print(f"✅ 렌더링 완료: {out_path}")
    return out_path


def render_inline(mermaid_code: str, name: str) -> Path:
    """인라인 Mermaid 코드를 받아 output/diagrams/{name}.html로 저장."""
    OUTPUT_DIAGRAMS.mkdir(parents=True, exist_ok=True)
    mmd_path = OUTPUT_DIAGRAMS / f"{name}.mmd"
    mmd_path.write_text(mermaid_code.strip(), encoding="utf-8")
    print(f"  .mmd 저장: {mmd_path}")
    return render_mmd(mmd_path)


def render_all() -> list[Path]:
    """output/diagrams/ 내 모든 .mmd 파일을 렌더링."""
    mmd_files = list(OUTPUT_DIAGRAMS.glob("*.mmd"))
    if not mmd_files:
        print("렌더링할 .mmd 파일이 없습니다.")
        return []
    results = []
    for f in sorted(mmd_files):
        try:
            results.append(render_mmd(f))
        except Exception as e:
            print(f"⚠️  {f.name} 렌더링 실패: {e}")
    return results


# ─── CLI ──────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Mermaid .mmd → HTML 렌더러")
    parser.add_argument("files", nargs="*", help=".mmd 파일 경로 (없으면 --all 필요)")
    parser.add_argument("--all", action="store_true", dest="all_files",
                        help="output/diagrams/ 내 모든 .mmd 처리")
    parser.add_argument("--inline", metavar="CODE",
                        help="인라인 Mermaid 코드 문자열 (--name과 함께)")
    parser.add_argument("--name", metavar="NAME",
                        help="인라인 모드 출력 파일명 (확장자 제외)")
    args = parser.parse_args()

    if args.inline:
        if not args.name:
            print("오류: --inline 사용 시 --name 옵션이 필요합니다.")
            sys.exit(1)
        out = render_inline(args.inline, args.name)
        print(f"📊 HTML: file://{out}")

    elif args.all_files:
        results = render_all()
        if results:
            print(f"\n📊 총 {len(results)}개 다이어그램 렌더링 완료:")
            for r in results:
                print(f"  file://{r}")

    elif args.files:
        for fp in args.files:
            try:
                out = render_mmd(Path(fp))
                print(f"📊 HTML: file://{out}")
            except Exception as e:
                print(f"⚠️  오류: {e}")

    else:
        parser.print_help()
        sys.exit(1)
